# Generated by Django 3.2 on 2021-07-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keyword',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
